import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./assets/styles/globals.css";
import Header from "./assets/components/layout/Header";
import Footer from "./assets/components/layout/Footer";
import { useState } from "react";
import Display from "./assets/components/Display";
// import Footer from './assets/components/layout/Footer'
// import Navbar from './assets/components/layout/nav/Navbar'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gestion de la salle de recette",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const accessGranted = true;

  return accessGranted ? (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Display>{children}</Display>
      </body>
    </html>
  ) : (
    <a href="https://myaccount.google.com/?utm_source=sign_in_no_continue&pli=1">
      Connexion
    </a>
  );
}
